name: tinodeflutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

flutter_native_splash:
  color: "#1a1c29"
  color_android: "#1a1c29"
  icon_background_color: "#1a1c29"
  fullscreen: true
  image: assets/image/background.png
  android_12:
    color: "#1a1c29"
    icon_background_color: "#1a1c29"
    image: assets/image/background.png
  android: true
  android_gravity: center
  color_dark: "#1a1c29"
  ios: true

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.2
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_it: ^7.2.0
  http: ^1.1.2
  package_info_plus: ^4.0.0
  permission_handler: ^11.0.0
  fluttertoast: 8.2.0
  easy_localization: ^3.0.2
  sprintf: ^6.0.0
  event_bus_plus: ^0.6.1
  scroll_to_index: ^3.0.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.5
  flutter_lints: ^2.0.0
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^6.1.1
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.0.1
  flutter_swipe_action_cell: ^3.1.3
  flutter_switch: ^0.3.2
  screen_brightness: ^1.0.0
  app_links: ^4.0.0
  flutter_inappwebview: ^5.0.3-nullsafety.1
  uni_links: ^0.5.1
  share_plus: ^7.2.2
  internet_connection_checker: ^1.0.0+1
  swipeable_page_route: ^0.4.2
  image_gallery_saver: '^2.0.3'
  image_size_getter: ^2.1.3
  in_app_purchase: ^3.2.0
  flutter_inapp_purchase: ^5.4.0
  swipe: ^0.0.1
  swipe_plus: ^0.8.1
  swipe_to: ^1.0.6
  drag_select_grid_view: ^0.6.2
  photo_gallery: ^2.1.1
  transparent_image: ^2.0.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.5
  carousel_slider: ^4.2.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  email_validator: ^2.0.1
  fast_image_resizer: ^0.0.2
  path_provider: ^2.1.1
  video_thumbnail: ^0.5.3
  image: ^4.1.3
  json_serializable: ^6.1.3
  modal_progress_hud_nsn: ^0.4.0
  cached_network_image: ^3.3.1
  chewie: ^1.7.4
  video_player: ^2.8.2
  visibility_detector: ^0.2.2
  flutter_downloader: ^1.11.6
  photo_view: ^0.14.0
  wechat_assets_picker: ^8.8.1+1
  wechat_camera_picker: ^4.2.1
  device_info_plus: ^9.1.1
  android_id: ^0.3.6
  url_launcher: ^6.2.5
  flutter_callkit_incoming: ^2.0.4+1
  agora_rtc_engine: ^6.0.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.10.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0



  rxdart: ^0.27.1
  web_socket_channel: ^2.2.0
  equatable: ^2.0.3
  logger: ^1.1.0
  intl: ^0.18.1
  objectbox: ^1.5.0
  objectbox_flutter_libs: any
  connectivity_plus: ^2.3.0
  qr_flutter: ^4.1.0

dependency_overrides:
  wechat_assets_picker: ^8.9.0-dev.1
  photo_manager: ^3.0.0-dev.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/image/
    - assets/image/svg/
    - assets/image/png/
    - assets/icons/

fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900