// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf223X5HxkTcGKt2fEQWdlcCTAJf_gc-k',
    appId: '1:360596887858:android:c97a2adca34b56f206df2b',
    messagingSenderId: '360596887858',
    projectId: 'jade-chat',
   // databaseURL: 'https://zempie.firebaseio.com',
    storageBucket: 'jade-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfNbQR7Wf-LyTLXgKS5RvJzLw3FIj77AQ',
    appId: '1:360596887858:ios:74f39ac40068812e06df2b',
    messagingSenderId: '360596887858',
    projectId: 'jade-chat',
  //  databaseURL: 'https://zempie.firebaseio.com',
    storageBucket: 'jade-chat.appspot.com',
    androidClientId: '360596887858-a90stdroi17j4jt5rahf26kkl76d50r6.apps.googleusercontent.com',
    iosClientId: '360596887858-8j8prv6nv3ra3stcfat60p4drpc78bd6.apps.googleusercontent.com',
    iosBundleId: 'com.widblack.jadechat',
  );
}